version: "3.8"

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-service
    ports:
      - "3001:3001" # Expose backend on port 3001
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    # Removed dependency on MongoDB since you're not using it

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "3000:3000" # Expose frontend on port 3000
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
    depends_on:
      - backend # Ensure backend is running before frontend starts
